[package]
name = "docs-exploit-demo"
version = "0.0.1"
authors = ["AlexApps99 <alex.apps99@gmail.com>"]
description = "An demo of how docs.rs could be used maliciously"
license = "Unlicense"
repository = "https://github.com/AlexApps99/docs-exploit-demo"
